version: '3'
services:
  mysql:
    image: mysql:5.6
    restart: always
    volumes:
      - ./sql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default
    ports:
      - '3306:3306'
  # # 需要 redis 的时候再放开
  # redis:
  #   image: redis
  #   restart: always
  #   ports:
  #     - 6379:6379
  #   command: redis-server
